spring:
  application:
    name: tukuntech-ms-support

  cloud:
    compatibility-verifier:
      enabled: false

  config:
    import: "optional:configserver:"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBIT_VHOST:/}

# --- MIRA AQU√ç: "ticket" debe estar pegado a la izquierda, NO dentro de spring ---
ticket:
  queue:
    name: cola-soporte
  exchange:
    name: exchange-soporte
  routing:
    key: ruta.ticket.creado

app:
  security:
    jwt:
      secret: ${JWT_SECRET}